# Generated by Django 2.2.6 on 2019-11-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
