# Generated by Django 2.1.3 on 2019-12-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='dt_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da devolução'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='km_devolucao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Km de devolução'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='qtd_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor_total_aluguel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
