# Generated by Django 2.2.6 on 2019-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controles', '0002_auto_20191122_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=13, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=13, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=13, verbose_name='RG'),
        ),
    ]
