# Generated by Django 2.2.6 on 2019-11-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controles', '0004_auto_20191123_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='numero_chassis',
            field=models.CharField(max_length=20, verbose_name='Número do chassis'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(max_length=20, verbose_name='Renavam'),
        ),
    ]
