# Generated by Django 2.2.6 on 2019-11-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controles', '0005_auto_20191123_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='valor_diaria',
            field=models.CharField(max_length=20, verbose_name='Valor da diária'),
        ),
    ]
