# Generated by Django 2.2.6 on 2019-11-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controles', '0006_auto_20191123_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='valor_diaria',
            field=models.IntegerField(verbose_name='Valor da diária'),
        ),
    ]
